export const AuthConstants = {
  expiresInDay: 60 * 60 * 24,
  successfulRegistration: 'User successfully registered',
  userAlreadyExistError: 'User already exists',
  wrongEmailOrPassword: 'Wrong email or password',
  emailField: 'email',
  emailConfirmationCodeField: 'emailConfirmationCode',
  somethingGoesWrong: 'Something goes wrong',
  googleIdField: 'googleId',
  userAlreadyExistsGoogleAccountWasNotConnected:
    'User already exists, but Google account was not connected to user account',
  emailConfirmationTokenExpiresInHours: 12,
  invalidToken: 'Invalid token',
  badRequest: 'Bad request',
  confirmEmailAddress: 'Please confirm your email address first',
  passwordSuccessfullyChanged: 'Password successfully changed',
  passwordNotChanged: 'Password is not changed',
  passwordSuccessfullyAdded: 'Password successfully added',
  useAnotherEmail: 'Please use another email',
  signedOut: 'Successfully signed out.',
  successfulVerification: 'Account was successfully verifying',
  verificationFailed: 'Verification failed',
  unauthorized: 'Unauthorized',
  forbiddenResource: 'Forbidden resource',
  verifyAccountFirst: 'Please verify account first',
  invalidGoogleToken: 'Invalid google token',
  emailSuccessfullyChanged: 'Email successfully changed',
  minForRandomSixDigitNumber: 100000,
  maxForRandomSixDigitNumber: 900000,
};
