export interface CreateDealInterface {
  accessionNumber: string;
  fileDate: Date;
  submissionType: string;
  cik: string;
  previousNames: string[];
  entityType: string;
  yearsOfIncorporation: string;
  issuerPhoneNumber: string;
  jurisdictionOfInc: string;
  dateOfFirstSale: Date;
  isMoreThanOneYear: boolean;
  isDealPublished: boolean;
  vanityName: string;
  dealAddress: string;
  regions: string | string[];
  status: string;
  assetClass: string;
  description: string;
  minimumInvestment: number;
  cashOnCash: number;
  investmentStructures: string | string[];
  fees: number;
  targetRaise: number;
  equityMultiple: number;
  holdPeriod: number;
  targetIRR: number;
  actualIRR: number;
  preferredReturn: number;
  dealLegalName: string;
  dealSponsor: string;
  exemption: string;
  secIndustry: string;
  closeDate: Date;
  regulation: string;
  street1?: string | '';
  street2?: string | '';
  city?: string | '';
  stateOrCountry?: string | '';
  stateOrCountryDescription?: string | '';
  zipCode?: string | '';
  sponsorId?: number;
}
