export interface CreateDealInterface {
  dealTitle?: string | null;
  dealAddress?: string | null;
  region: string | null;
  status: string | null;
  assetClass: string | null;
  description?: string | null;
  minimumInvestment?: number | null;
  cashOnCash?: number | null;
  investmentStructure: string | null;
  fees?: number | null;
  targetRaise?: number | null;
  equityMultiple?: number | null;
  holdPeriod: string | null;
  targetIRR?: number | null;
  actualIRR?: number | null;
  dealLegalName?: string | null;
  dealSponsor?: string | null;
  exemption?: string | null;
}
