export interface CreateSponsorInterface {
  vanityName: string;
  legalName: string;
  userId: number;
  businessAvatar: string;
  businessEmail: string;
  businessPhone: string;
  sponsorName: string;
  address: string;
  website: string;
  description: string;
  aum: number;
  specialties: string | string[];
  facebookLink: string;
  linkedInLink: string;
  twitterLink: string;
  instagramLink: string;
  workForThisCompany: boolean;
  regions: string | string[];
  equityMultiple: number;
  averageIRR: number;
  interests: string | string[];
  street1: string;
  street2: string;
  city: string;
  stateOrCountry: string;
  stateOrCountryDescription: string;
  zipCode: string;
  yearOfFoundation: number;
}
