export enum AssetClasses {
  buildToRent = 'Build-to-Rent',
  coLiving = 'Co-Living',
  dataCenter = 'Data Center',
  flexRD = 'Flex R&D',
  flexOffice = 'Flex/Office',
  hospitality = 'Hospitality',
  industrial = 'Industrial',
  landManufacturedHousing = `Land'Manufactured Housing`,
  medicalOffice = 'Medical Office',
  mixedUse = 'Mixed Use',
  multiAsset = 'Multi-Asset',
  multifamily = 'Multifamily',
  office = 'Office',
  parkingGarage = 'Parking Garage',
  retail = 'Retail',
  senionHousing = 'Senior Housing',
  singleFamily = 'Single Family',
  specialty = 'Specialty',
  storage = 'Storage',
  mobileHome = 'Mobile Home',
}
